% MISC
%
% Files
%   applycolourmap         - Applies colourmap to a single channel image to obtain an RGB result
%   basename               - Trims off the .ending of a filename
%   bbspline               - Basic B-spline
%   bilateralmap           - Generates a bilateral colourmap
%   chirpexp               - Generates exponential chirp test image
%   chirplin               - Generates linear chirp test image
%   circle                 - Draws a circle.
%   circlesineramp         - Generates test image for evaluating cyclic colour maps
%   circularstruct         - CIRCULARSTRUCT
%   cloud9                 - Cloud movie of 1/f noise.
%   clouds                 - CLOUDS
%   cmyk2rgb               - Basic conversion of CMYK colour table to RGB
%   cubicroots             - finds real valued roots of cubic
%   dbscan                 - DBSCAN clustering algorithm
%   deres                  - Deresolves an image.
%   derespolar             - Desresolves image in polar coordinates.
%   digipts                - digitise points in an image
%   fillnan                - fills NaN values in an image with closest non Nan value
%   findimage              - invokes image dialog box for interactive image loading
%   findimages             - invokes image dialog box for multiple image loading
%   geoseries              - Generate geometric series
%   geosofttbl2map         - Converts Geosoft .tbl file to MATLAB colourmap
%   graymap                - Generates a gray colourmap over a specified range
%   hsvmap                 - Generates an HSV colourmap over a specified range of hues
%   implace                - place image at specified location within larger image
%   imwritefloattiff       - Write single channel floating point data to a tiff file
%   imwritesc              - Writes an image to file, rescaling if necessary.
%   labmap                 - Generates a colourmap based on L*a*b* space
%   lms2rgb                - LMS to RGB colour space conversion
%   logcolournormalization - Chromaticity, grey, or comprehensive colour normalization.
%   map2geosofttbl         - Converts MATLAB colourmap to Geosoft .tbl file
%   matprint               - prints a matrix with specified format string
%   matscii                - Function to generate ASCII images
%   namenpath              - Returns filename and its path from a full filename
%   noiseonf               - Creates 1/f spectrum noise images.
%   orientationplot        - Visualizes orientation image with dithered oriented lines
%   pathlist               - Produces a cell array of directories along a directory path
%   pbspline               - Basic Periodic B-spline
%   pointinconvexpoly      - Determine if a 2D point is within a convex polygon
%   polartrans             - Transforms image to polar coordinates
%   polyfit2d              - Fits 2D polynomial surface to data
%   polyval2d              - Evaluates 2D polynomial surface generated by POLYFIT2D
%   randmap                - Generates a colourmap of random colours
%   rectintersect          - Returns true if rectangles intersect
%   removenan              - removes NaNs from an array 
%   rgb2cmyk               - Basic conversion of RGB colour table to cmyk 
%   rgb2lab                - RGB to L*a*b* colour space
%   rgb2lms                - RGB to LMS colour space conversion
%   rgb2nrgb               - RGB to normalised RGB
%   show                   - Displays an image with the right size, colors, range, and with a title.
%   showangularim          - Displays image of angular data
%   showdivim              - Displays image with diverging colour map
%   showfft                - Displays amplitude spectrum of an fft.
%   showlogfft             - Displays log amplitude spectrum of an fft.
%   showsurf               - shows parametric surface in a convenient way
%   sineramp               - Generates sine on a ramp colour map test image
%   strendswith            - tests if a string ends with a specified substring
%   strstartswith          - tests if a string starts with a specified substring
%   superquad              - generates a superquadratic surface
%   supertorus             - generates  a 'supertorus' surface
%   svddemo                - DEMO of SVD and eigenvalues for a 2x2 transformation matrix
%   syncshow               - Show multiple images/figures with axes linked for pan and zoom
%   testdbscan             - Program to test/demonstrate the DBSCAN clustering algorithm
%   togglefigs             - Convenient switching between figures to aid comparison
%   viewlabspace           - Visualisation of L*a*b* space
%   viewlabspace2          - Visualisation of L*a*b* space
%   weightedhistc          - Weighted histogram count
%   xyz2lms                - XYZ to LMS colour space conversion
